In [1]:
import torch
import numpy as np

### tensor 정의하기

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [6]:
np_array = np.array(data)
print(np_array)

[[1 2]
 [3 4]]


In [8]:
x_ones = torch.ones_like(x_data)
print(x_ones)

tensor([[1, 1],
        [1, 1]])


In [9]:
tensor = torch.rand(3,4)
print(tensor)

tensor([[0.8158, 0.4369, 0.9672, 0.8723],
        [0.2881, 0.7760, 0.5475, 0.7304],
        [0.7666, 0.1864, 0.0842, 0.6754]])


### tensor cuda에 저장하기

In [10]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print('Success!')

### tensor 수정하기

In [13]:
tensor = torch.ones(4,4)
print(tensor)
tensor[:, 1] = 0
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### tensor 합치기

In [15]:
t1 = torch.cat([tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.]])


### tensor 연산

In [18]:
t = torch.ones(5)
print(t)
print(t.add(1))

tensor([1., 1., 1., 1., 1.])
tensor([2., 2., 2., 2., 2.])
